### ISSUE TITLE
Missing nerfs from the update on the 28th

### ISSUE THREAD

**Issue by Heionbuji** [user6174/shadowverse-json#1]
Hey, do you have any intention of keeping this updated? 
I don't mind a little delay, but if you won't be updating it anymore I'd like to know, so I can start working on it myself.

**Comment by user6174** [comment]
My bad, I was just forgetting to update. I'll upload the new jsons as soon as they're built.

**Comment by Heionbuji** [comment]
Awesome, thanks.
